### ISSUE TITLE
[Aurascan][CW20][TokensList][TokenDetails] Some UI issues

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#1352]
Link: https://serenity.aurascan.io/tokens

**Search field**
- [x] ISSUE 01: Chỉnh màu background của price: #5EE6D0 20%
- [x] ISSUE 02: Chỉnh màu viền: #67C091
- [ ] ISSUE 03: Thêm tick màu xanh với contract đã được verified: width: 16px; height: 16px; background: #67C091
- [ ] ISSUE 04: Thêm web link của token: màu text: Global/Grayscale/Grey-6
- [ ] ISSUE 05: Address của token: hiển thị full, màu text Global/Grayscale/Grey-6
![image](https://user-images.githubusercontent.com/24869170/205618712-21456e70-68e0-4243-bb0f-ecb53fd3ea81.png)

**Tokens list:**

- [x] ISSUE 06: xem ảnh đính kèm

![image](https://user-images.githubusercontent.com/24869170/205622230-12ef1262-d52c-41f4-b221-f7f9f2a43f7a.png)

**Token details:**
- [x] ISSUE 07: Price: Thêm số phần trăm tăng/giảm
- [x] ISSUE 08: Holders: Thêm số phần trăm tăng/giảm
- [x] ISSUE 09: Bỏ số 0 ở sau dấu phẩy (hiển thị tối đa 6 số lẻ)
![image](https://user-images.githubusercontent.com/24869170/205787328-3664f08f-c989-4b7c-882a-2c21bfa6bf0d.png)

**Comment by mtamkg** [comment]
ISSUE 3/4/5 liên quan đến layout mới, nên tạm thời sẽ ko fix

**Comment by Dpthao245** [comment]
PASS in Serenity 12/12/2022
ISSUE 01, 02

![Image](https://user-images.githubusercontent.com/72438169/207007020-9fe5645e-f760-4d17-be7f-2367e416d305.png)

ISSUE 06

ISSUE 07, 08, 09

![Image](https://user-images.githubusercontent.com/72438169/207008650-014c7713-6544-483a-8817-6ea4494c4a6b.png)

**Comment by ntatfff** [comment]
Verified PASS on Euphoria (27/12/2022)
![image](https://user-images.githubusercontent.com/24869170/209622933-41e3ad18-8a32-42d2-8baa-66e9f85351a1.png)
