### ISSUE TITLE
[Aurascan][Dashboard][Desktop] Some UI issues are not as designed

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/aurascan#746]
**Describe the bug**
Some UI issues are not as designed

**To Reproduce**
1. Check dashboard screen on desktop
2.  See error

**Expected behavior**
- [x] 1. Search field #24262E
- [x] 2. Text của menu: font-weight 600
- [x] 3. màu text của menu (cái không được select): #717582
- [x] 4. số cột bên trái biểu đồ: font-size 14px; line-height: 16px
- [x] 5. số nằm ngang biểu đồ: font-size 14px; #868A97
- [ ] 6. màu nền từ line chart đến trục ngang: xanh nhạt hơn
- [x] 7. Màu button: + - download #868A97
- [x] 8. text number ở 4 box: Line height28px
- [x] 9. text "View more" font-weight: 600
- [x] 10. chữ trong bảng: line-height: 16px;
- [x] 11. màu header của bảng và button giống nhau

**Screenshots**
- Desktop
![image](https://user-images.githubusercontent.com/24869170/182520254-36dec9d4-a59f-4c9f-b531-b74529a22817.png)
- Figma
![image](https://user-images.githubusercontent.com/24869170/182520362-4eabb559-daaa-4f90-820b-589b73f8f3cd.png)
