### ISSUE TITLE
[Aurascan][Mobile][ProposalList][ProposalDetail] Some issues update layout

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#753]
**Proposal List**

- [x] ISSUE 01: Layout UI của Proposal Table sai hoàn toàn so với Design
![image](https://user-images.githubusercontent.com/72438169/182579753-e839cc1e-7c21-4af1-b105-590f8e948878.png)

- [x] ISSUE 02: Vị trí text và màu không đúng với Design -> Size 14px, Weight 400, #868A97
![Image](https://user-images.githubusercontent.com/72438169/183578722-72dbf125-2333-4d20-8ae4-0e611631b911.png)
![Image](https://user-images.githubusercontent.com/72438169/183578771-229df0d3-b34d-4a45-88a0-18287eb71821.png)

- [x] ISSUE 03: Sai font size, weight -> 12px, 400
![Image](https://user-images.githubusercontent.com/72438169/183579342-b7b9fed3-fd92-4c6b-8ce7-baa2b997b8d7.png)

- [x] ISSUE 04: Sai weight -> 600
![Image](https://user-images.githubusercontent.com/72438169/183579818-524047c0-7f25-49ea-8c80-b2510c2dccda.png)

**Proposal Detail**

- [x] ISSUE 01: Kết quả vote để dấu " "
![Image](https://user-images.githubusercontent.com/72438169/183581421-5d570596-18a9-4e9e-b810-4a4b5fcc253f.png)

- [x] ISSUE 02: Sai màu text -> #67C091
![Image](https://user-images.githubusercontent.com/72438169/183554838-b6927a94-b823-4e5b-91e4-27d60e470fbe.png)

- [x] ISSUE 03: Sai màu text -> #9DA1AC
![Image](https://user-images.githubusercontent.com/72438169/183556008-24768921-5ecd-4a0b-a3e4-f4a3aa116d37.png)

- [x] ISSUE 04: Sai font size 14px, weight 500 -> 16px, 400
![Image](https://user-images.githubusercontent.com/72438169/183556096-d47823a9-9e7d-48d8-9f00-255c99d77b21.png)

- [x] ISSUE 05: Sai màu text -> #E5E7EA
![Image](https://user-images.githubusercontent.com/72438169/183557769-7ba24061-25fe-4db9-a3d4-26c20545e6f9.png)

- [x] ISSUE 06: Sai màu text -> #9EDBB8
![Image](https://user-images.githubusercontent.com/72438169/183558426-eee2bd47-0781-41ac-bd00-58b23ee6da70.png)

- [x] ISSUE 07: Sai màu text -> #E5E7EA
![Image](https://user-images.githubusercontent.com/72438169/183558648-023b4e92-951a-42a6-9d09-206575e69296.png)

- [x] ISSUE 08: Sai màu text -> #E5E7EA
![Image](https://user-images.githubusercontent.com/72438169/183559022-477d01f3-7bd6-4ade-b638-368c31e39e6c.png)

- [x] ISSUE 09: Sai màu text -> #868A97
![Image](https://user-images.githubusercontent.com/72438169/183559248-c7825674-e8e3-45dc-89bc-7e04f035f66f.png)

- [x] ISSUE 10: Canh giữa -> Canh trái
![Image](https://user-images.githubusercontent.com/72438169/183559523-9a005c41-c8bc-4e2b-86d9-56356b39773c.png)

**Comment by Dpthao245** [comment]
Mobile

- [ ] ISSUE 11: Sai màu text -> #9DA1AC
![Image](https://user-images.githubusercontent.com/72438169/183562910-5688546d-54de-4012-bb36-6f54691bd1ec.png)

- [ ] ISSUE 12: Không load được avatar default của validator
![Image](https://user-images.githubusercontent.com/72438169/183562466-ca851123-c261-4107-9d84-5242d49fd988.png)

**Comment by Dpthao245** [comment]
**PASS in Dev 23/08/2022**

**Proposal List**

**ISSUE 01**
![image](https://user-images.githubusercontent.com/72438169/186066765-bbacd732-b3c7-4d36-abc8-6577858fd349.png)

**ISSUE 03**
![image](https://user-images.githubusercontent.com/72438169/186067867-d66a58de-546b-498b-8e6d-127ee3256d77.png)

**ISSUE 04**
![image](https://user-images.githubusercontent.com/72438169/186067847-e01492ca-4970-42e2-9c79-f4d254c5a192.png)

**Proposal Detail**

ISSUE 02
![image](https://user-images.githubusercontent.com/72438169/186068389-521ca4c5-38c4-44f4-aecc-a150e027a60d.png)

ISSUE 04
![image](https://user-images.githubusercontent.com/72438169/186068692-93dca062-8799-4623-8f16-9da259f0509b.png)

ISSUE 05
![image](https://user-images.githubusercontent.com/72438169/186068816-71e3f478-513b-4bf6-87d6-f6d45da6d2ed.png)

ISSUE 07
![image](https://user-images.githubusercontent.com/72438169/186069173-c10e7cb7-dcfa-47bc-a53f-adf294b4b25a.png)

ISSUE 08
![image](https://user-images.githubusercontent.com/72438169/186069295-559f34ad-7dd2-4426-9bee-80d9cec36d5c.png)

ISSUE 09
![image](https://user-images.githubusercontent.com/72438169/186069388-e4152975-45df-4110-a193-e6e9baee612c.png)

ISSUE 10
![image](https://user-images.githubusercontent.com/72438169/186069489-f916c2d4-1328-450a-aa09-841aebaa3e74.png)

**Comment by Dpthao245** [comment]
FAIL in Dev 23/08/2022
**Proposal List**

- [ ] ISSUE 02: Màu #FFFFFF -> #868A97

![image](https://user-images.githubusercontent.com/72438169/186067488-b9249928-6680-45f3-9363-48ccc99e4a9d.png)

**Proposal Detail**

- [ ]  ISSUE 01: Không hiển thị kết quả Vote để test -> Kết quả vote để dấu " "

![image](https://user-images.githubusercontent.com/72438169/186068167-678fc184-58e1-4a85-b6c0-269e3457285b.png)

- [ ] ISSUE 03: Sai màu text -> #9DA1AC
![image](https://user-images.githubusercontent.com/72438169/186068558-9ca94d46-8bd0-4db9-8f1a-79af19e0a278.png)

- [ ] ISSUE 06: Sai màu text -> #9EDBB8
![image](https://user-images.githubusercontent.com/72438169/186068951-6f843cec-6be3-4c60-a02a-77ec321fca54.png)

**Comment by Dpthao245** [comment]
PASS in Dev 23/08/2022

ISSUE 02
![image](https://user-images.githubusercontent.com/72438169/186096335-ab4efddb-696a-4867-b667-173540da9d60.png)

ISSUE 01
![image](https://user-images.githubusercontent.com/72438169/186096591-aa3ad797-112b-4e0b-9e83-bacecb1ac00e.png)

ISSUE 03
![image](https://user-images.githubusercontent.com/72438169/186096778-79d0db0c-98e6-42e1-a354-85bc44c3b4ce.png)

FAIL

- [ ] ISSUE 06: Sai màu text -> #9EDBB8
![image](https://user-images.githubusercontent.com/72438169/186097261-580bb0bb-878c-48e2-9a7f-8b279df619ef.png)
