### ISSUE TITLE
[Aurascan][Mobile][ProposalDetail] Some issues update layout

### ISSUE THREAD

**Issue by Dpthao245** [aura-nw/aurascan#776]
Proposal Detail

- [x] ISSUE 01: Sai màu text -> #9DA1AC
![Image](https://user-images.githubusercontent.com/72438169/183581696-f63f421e-c2bd-4945-898a-d7cb59e7ce74.png)

- [x] ISSUE 02: Không load được avatar default của validator
![Image](https://user-images.githubusercontent.com/72438169/183562466-ca851123-c261-4107-9d84-5242d49fd988.png)

- [x] ISSUE 03: Sai weight, màu -> 400, #E5E7EA
![Image](https://user-images.githubusercontent.com/72438169/183582555-442c8493-072d-4069-86a2-5cac01263ec0.png)

- [x] ISSUE 04: Vị trí text không đúng
![Image](https://user-images.githubusercontent.com/72438169/183582919-5e48a96a-45be-4348-92ba-efdd149da41d.png)

- [x] ISSUE 05: Sai font size, weight, màu

![Image](https://user-images.githubusercontent.com/72438169/183583720-cbbbea95-66fc-4129-8ad5-5d0be63be98b.png)

- [x] ISSUE 06: Sai màu -> #67C091
![Image](https://user-images.githubusercontent.com/72438169/183583964-af02fa66-136a-49ce-9ce7-05126835b146.png)

- [x] ISSUE 07: Sai màu -> #868A97
![Image](https://user-images.githubusercontent.com/72438169/183584557-371cee80-16b4-462e-8e15-cc7a5e0e8ac6.png)

- [x] ISSUE 08: Kích thước thanh lớn -> 20px
![Image](https://user-images.githubusercontent.com/72438169/183585240-36ad371c-838e-44d2-b7b6-c159de495812.png)

- [x] ISSUE 09: Sai weight -> 400
![Image](https://user-images.githubusercontent.com/72438169/183585790-e4b06dcb-f3fb-406e-8e6e-6d84f7ac7b89.png)

- [x] ISSUE 10: text canh giữa, sai weight, màu -> canh phải, 500, #E5E7EA
![Image](https://user-images.githubusercontent.com/72438169/183586247-ba728595-6cd0-4c59-8da2-fb4a86fa32f9.png)

- [x] ISSUE 11: Sai weight, màu -> 400, #868A97
![Image](https://user-images.githubusercontent.com/72438169/183586498-7dda5296-cbe8-4f49-a9a4-edeba367264e.png)

- [x] ISSUE 12: Sai text "Current Status" và vị trí hiển thị status proposal
![Image](https://user-images.githubusercontent.com/72438169/183587166-a9ba4ca2-6984-4e07-a7fe-2dabc32aa878.png)

- [x] ISSUE 13: Sai màu text -> #D5625E
![Image](https://user-images.githubusercontent.com/72438169/183587742-00b1c175-7517-468c-b1e7-286eebe7e991.png)

- [x] ISSUE 14: Sai màu text -> #D5625E
![Image](https://user-images.githubusercontent.com/72438169/183587980-bb06117c-8b07-44b4-826e-647efa1ed96a.png)

- [x] ISSUE 15: Sai màu text -> #868A97
![Image](https://user-images.githubusercontent.com/72438169/183592528-25f742bd-4382-4fa8-a8cc-6eec5544a0bf.png)

- [x] ISSUE 16: Sai font size, weight ->14px, 500
![Image](https://user-images.githubusercontent.com/72438169/183592991-05cc494d-21be-4cd7-a0fa-e2ace7b48752.png)

- [x] ISSUE 17: Sai màu -> #868A97
![Image](https://user-images.githubusercontent.com/72438169/183593208-5f1f5426-25af-4d88-8eb9-e60cf7eb9372.png)

- [x] ISSUE 18: Sai vị trí và kích thước nút Vote
![Image](https://user-images.githubusercontent.com/72438169/183593747-74b5db7c-54fa-47ef-b0db-df73468805f0.png)

**Comment by Dpthao245** [comment]
PASS in Dev 22/08/2022

ISSUE 01
![image](https://user-images.githubusercontent.com/72438169/185874181-5a77de1b-b62a-407b-89c5-c206e07b287c.png)

ISSUE 02
![image](https://user-images.githubusercontent.com/72438169/185874393-28dfdfa0-3045-4e42-841d-2ee07f108517.png)

ISSUE 03
![image](https://user-images.githubusercontent.com/72438169/185874762-82c215f1-8b07-4277-b936-a5fe472b566e.png)

ISSUE 04
![image](https://user-images.githubusercontent.com/72438169/185875617-60a82743-02f8-4545-b17b-76eeb951ec56.png)

ISSUE 05
![image](https://user-images.githubusercontent.com/72438169/185876008-f1ee4fd1-580f-4a62-8408-be2b4cfe046c.png)
![image](https://user-images.githubusercontent.com/72438169/185876343-62f8aa4a-7497-4277-8d28-2c15c4074ca7.png)

ISSUE 06
![image](https://user-images.githubusercontent.com/72438169/185876559-f8bc5f34-abac-454d-aecf-3bf1beb5f4a5.png)

ISSUE 07
![image](https://user-images.githubusercontent.com/72438169/185876796-b0a65c43-da98-43b5-9a73-e04012c99f00.png)

ISSUE 08
![image](https://user-images.githubusercontent.com/72438169/185877504-afaef585-ee7c-4137-90fd-dddb2c982e5e.png)

ISSUE 09
![image](https://user-images.githubusercontent.com/72438169/185877735-a2e4a440-4ac7-48f4-ac26-6ab8a5e174f7.png)

ISSUE 12
![image](https://user-images.githubusercontent.com/72438169/185879014-2b2894f5-44dd-43ee-9b79-5e82fbe2996b.png)

ISSUE 15
![image](https://user-images.githubusercontent.com/72438169/185881146-f548ae0c-bc1b-49de-bdcb-144dbb1f92e2.png)

ISSUE 16
![image](https://user-images.githubusercontent.com/72438169/185881478-8b0959ed-ed77-49a8-8f84-ee492b9eb15b.png)

ISSUE 18
![image](https://user-images.githubusercontent.com/72438169/185881906-f0f0acf3-8ce3-4537-8f75-59299446c534.png)

**Comment by Dpthao245** [comment]
FAIL in Dev 22/08/2022

- [ ] ISSUE 10: Canh giữa -> canh phải
![image](https://user-images.githubusercontent.com/72438169/185878418-37f07420-e723-4cc4-a009-6d5da1edb78b.png)

- [ ]  ISSUE 11: Sai  màu ->#868A97
![image](https://user-images.githubusercontent.com/72438169/185878839-1e3bf57e-1dde-4e36-a66d-78c9ac532ec1.png)

- [ ] ISSUE 13: Sai màu text -> #D5625E
![image](https://user-images.githubusercontent.com/72438169/185880053-c0d62812-eef0-4e0c-b6be-66002f6a5d05.png)

- [ ] ISSUE 14: Sai màu, font size, weight -> #868A97, 14px / 400
![image](https://user-images.githubusercontent.com/72438169/185880827-6953f423-3cac-4b89-8f8d-7e9c5bc3f4d3.png)

- [ ] ISSUE 17: Sai màu -> #868A97
![image](https://user-images.githubusercontent.com/72438169/185881645-f07fd75e-d2aa-496d-b724-d18159326545.png)

- [ ] ISSUE 19: Sai weight -> 500
![image](https://user-images.githubusercontent.com/72438169/185879816-cb89a49b-71dc-4f53-b321-d834fff43844.png)

- [ ] ISSUE 20: Sai màu, weight -> #E5E7EA, 500
![image](https://user-images.githubusercontent.com/72438169/185879500-daf4092f-f0e6-45d8-acdb-354e4d3c0b38.png)

**Comment by Dpthao245** [comment]
**PASS in Dev 23/08/2022**

ISSUE 10
![image](https://user-images.githubusercontent.com/72438169/186083637-d0e19b91-3ab0-43a6-8bfc-09038e053a55.png)

ISSUE 11
![image](https://user-images.githubusercontent.com/72438169/186084060-2a39e54b-2157-4b6a-b376-3403873330bb.png)

ISSUE 13
![image](https://user-images.githubusercontent.com/72438169/186084185-24bb3255-c351-4192-b9de-3b4ab1a712ec.png)

ISSUE 17
![image](https://user-images.githubusercontent.com/72438169/186085163-ce20bf78-6443-46b6-b0b0-67d6e8dd3a5a.png)

ISSUE 19
![image](https://user-images.githubusercontent.com/72438169/186085300-ba127472-8620-4abe-955e-eaf119603733.png)

ISSUE 20
![image](https://user-images.githubusercontent.com/72438169/186085447-7f23eed3-c159-4bac-8009-7acc8dee5b82.png)

ISSUE 21
![image](https://user-images.githubusercontent.com/72438169/186085605-893e726b-3456-4ea9-9271-967dd461895e.png)

**Comment by Dpthao245** [comment]
**FAIL in Dev 23/08/2022**

- [ ] ISSUE 14: Sai font size, weight -> 14px / 400

![image](https://user-images.githubusercontent.com/72438169/186084620-84346c1e-ea84-41ab-bb98-dfcfb0c5e8f4.png)

- [ ] ISSUE 21: % rớt hàng
![image](https://user-images.githubusercontent.com/72438169/186085815-d921418c-84d1-4942-b4bf-adaaaa761c61.png)

**Comment by Dpthao245** [comment]
PASS in Dev 23/08/2022

ISSUE 14


![Image](https://user-images.githubusercontent.com/72438169/186105443-2db08f24-5220-4985-a264-50cc52a1eca1.png)


ISSUE 21


![Image](https://user-images.githubusercontent.com/72438169/186105238-dcf40460-f787-4d5f-ac47-743ba53dac2a.png)
